theme: jekyll-theme-architect

# Site
title: xchens
subtitle: blog
description: cshsonice的技术分享博客
keywords: [blog, 技术, c++, python] 
author: cshsonice
language: zh-CN
timezone:
url: https://xchens.cn
paginate: 5
paginate_path: "/page:num"
permalink: pretty



