theme: jekyll-theme-architect

# Site
title: xchens
subtitle: 
description: 陈实的博客
keywords: blog
author: xchens
language: 
timezone:

index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
per_page: 10
pagination_dir: page

favicon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1538501031893&di=a38a375ad1d3194ab845c09da58cced2&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dshijue1%252C0%252C0%252C294%252C40%2Fsign%3Deb3e9b0dba7eca80060831a4f94afda8%2F64380cd7912397ddf86ba52a5382b2b7d0a28789.jpg
