theme: jekyll-theme-architect

# Site
title: xchens
subtitle: blog
description: 人无远虑，必有近忧
keywords: blog
author: 陈实
language: 
timezone:
url: https://xchens.cn

markdown: kramdown
# kramdown:
#     input: GFM
# highlighter: rouge


