theme: jekyll-theme-architect

# Site
title: xchens
subtitle: blog
description: 人无远虑，必有近忧
keywords: [blog, 技术, c++, python] 
author: 陈实
language: zh-CN
timezone:

links_title: 友情链接
links:
  mygithub: https://github.com/cshsonice
  myzhihu: https://www.zhihu.com/people/chen-sh-55/activities






