theme: jekyll-theme-architect

# Site
title: xchens
subtitle: blog
description: 人无远虑，必有近忧
keywords: blog
author: 陈实
language: 
timezone:

index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
per_page: 10
pagination_dir: page


